######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 25 22:16:12 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include/core src/core
INCLUDEPATH += . include/core

# Input
HEADERS += include/core/mainWindow.hpp
SOURCES += src/core/main.cpp src/core/mainWindow.cpp
