######################################################################
# Automatically generated by qmake (3.0) mer. nov. 26 15:06:16 2014
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Casper
INCLUDEPATH += . include/gui

# Input
HEADERS += include/gui/mainWindow.hpp
SOURCES += src/gui/main.cpp src/gui/mainWindow.cpp
